version: '{build}'
branches:
  only:
  - master
  - develop
image: Previous Visual Studio 2019
platform: x64
configuration: Release
build_script:
- cmd: >-
    cd C:\projects\numcpp &&
    mkdir build &&
    cd build &&
    cmake .. -DBUILD_TESTS=ON -DBUILD_EXAMPLE_GAUSS_NEWTON_NLLS=ON -DBUILD_EXAMPLE_README=ON -DBOOST_ROOT=C:\Libraries\boost_1_73_0 &&
    cmake --build . --config Release &&
    cmake --build . --target install
test_script:
- cmd: >-
    cd ..\test\pytest &&
    C:\Python37-x64\python -m pytest
