version: '{build}'
branches:
  only:
  - master
image: Previous Visual Studio 2019
platform: x64
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake .. -DBUILD_EXAMPLE_GAUSS_NEWTON_NLLS=True -DBUILD_EXAMPLE_README=True -DBOOST_ROOT=C:\Libraries\boost_1_73_0
    
    cmake --build . --config Release --target GaussNewtonNlls

    cmake --build . --config Release --target ReadMe
    
    cmake --build . --config Release --target install
test: off